name: country_codes_plus
description: Country code plus is a helper package that provides country details given a particular localization, such as dial codes, ISO 3166 codes (alpha-2, alpha-3) and country names.
version: 5.0.3
homepage: https://github.com/seidlmatus/country_code_plus
repository: https://github.com/seidlmatus/country_code_plus
issue_tracker: https://github.com/seidlmatus/country_code_plus/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.miguelruivo.flutter.plugin.countrycodes.country_codes_plus
        pluginClass: CountryCodesPlugin
      ios:
        pluginClass: CountryCodesPlugin
      macos:
        pluginClass: CountryCodesPlugin
